# Prediction of Real State Prices in Portugal

The current project involves preparing the necessary data and training a supervised model to predict the price of a real estate property based on various variables. 

We will use the LightGBM algorithm, which is an optimized implementation of gradient boosting. This algorithm is based on an ensemble of decision trees that are trained sequentially, with each tree learning to correct the errors of the previous ones. LightGBM is particularly effective due to its ability to handle large datasets, work with sparse features, and capture complex patterns in the data efficiently.

# Table of contents

- [Libraries and functions](#libraries-and-functions)
- [Loading and initial approach to data](#loading-and-initial-approach-to-data)
- [Imputation of nulls](#imputation-of-nulls)
- [Encoding qualitative variables](#encoding-qualitative-variables)
- [Outliers](#outliers)
- [Preparing the dataset for the model](#preparing-the-dataset-for-the-model)
- [Training the model](#training-the-model)
- [Evaluating the model](#evaluating-the-model)
- [Splitting the dataset into three ranges](#splitting-the-dataset-into-three-ranges)
- [Conclusions](#conclusions)

## Libraries and functions

In [240]:
import pandas as pd
import polars as pl
import numpy as np
from datetime import datetime
import re
from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from lightgbm.callback import early_stopping
from lightgbm import log_evaluation
from sklearn.preprocessing import StandardScaler

In [241]:
def poor_columns(df):
    threshold = 0.5 * df.height
    poor_columns = [c for c in df.columns if df.select(pl.col(c).is_null().sum()).item() > threshold]
    return display(poor_columns)

In [242]:
def codificar_floor(floor):
    floor = str(floor).lower() 
    if floor == 'no':  
        return 0 
    elif "basement level" in floor: 
        return -1
    elif "ground floor" in floor:  
        return 0
    elif "mezzanine" in floor:  
        return 0.5
    elif "top floor" in floor:  
        return 15
    elif "attic" in floor:  
        return 15
    elif "above 10th floor" in floor:  
        return 15  
    elif "service floor" in floor:  
        return 1
    elif "triplex" in floor:  
        return 15
    elif "duplex" in floor:  
        return 15
    else:
        match = re.search(r"(\d+)", floor)
        return float(match.group(1)) if match else None

In [243]:
def codificar_energy_certificate(cert):
    if cert is None or cert.lower() in ["no certificate", "not available", "nc"]:
        return -1
    cert = cert.upper() 
    mapping = {
        "A+": 1,
        "A": 2,
        "B": 3,
        "B-": 4,
        "C": 5,
        "D": 6,
        "E": 7,
        "F": 8,
        "G": 9
    }
    return mapping.get(cert, -1)

## Loading and initial approach to data

In [244]:
df_house = pl.read_csv('portugal_housing.csv')
df_house.sample(5)

shape: (5, 25)
┌──────────┬──────────┬────────────┬────────────┬───┬────────────┬─────────┬───────────┬───────────┐
│ Price    ┆ District ┆ City       ┆ Town       ┆ … ┆ LivingArea ┆ LotSize ┆ BuiltArea ┆ NumberOfB │
│ ---      ┆ ---      ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---     ┆ ---       ┆ athrooms  │
│ f64      ┆ str      ┆ str        ┆ str        ┆   ┆ f64        ┆ str     ┆ str       ┆ ---       │
│          ┆          ┆            ┆            ┆   ┆            ┆         ┆           ┆ f64       │
╞══════════╪══════════╪════════════╪════════════╪═══╪════════════╪═════════╪═══════════╪═══════════╡
│ 125000.0 ┆ Faro     ┆ Lagos      ┆ São        ┆ … ┆ null       ┆ null    ┆ null      ┆ null      │
│          ┆          ┆            ┆ Gonçalo de ┆   ┆            ┆         ┆           ┆           │
│          ┆          ┆            ┆ Lagos      ┆   ┆            ┆         ┆           ┆           │
│ 319900.0 ┆ Porto    ┆ Gondomar   ┆ Rio Tinto  ┆ … ┆ 196.0      ┆ 283.0   ┆ null      ┆ 3.0       │
│ 945000.0 ┆ Faro     ┆ Vila do    ┆ Vila do    ┆ … ┆ 468.0      ┆ 1221.0  ┆ null      ┆ 7.0       │
│          ┆          ┆ Bispo      ┆ Bispo e    ┆   ┆            ┆         ┆           ┆           │
│          ┆          ┆            ┆ Raposeira  ┆   ┆            ┆         ┆           ┆           │
│ 115000.0 ┆ Aveiro   ┆ Ovar       ┆ Ovar, São  ┆ … ┆ null       ┆ 1527.0  ┆ null      ┆ 0.0       │
│          ┆          ┆            ┆ João,      ┆   ┆            ┆         ┆           ┆           │
│          ┆          ┆            ┆ Arada e    ┆   ┆            ┆         ┆           ┆           │
│          ┆          ┆            ┆ São Vi…    ┆   ┆            ┆         ┆           ┆           │
│ 398500.0 ┆ Bragança ┆ Bragança   ┆ Santa      ┆ … ┆ 840.0      ┆ null    ┆ null      ┆ 6.0       │
│          ┆          ┆            ┆ Comba de   ┆   ┆            ┆         ┆           ┆           │
│          ┆          ┆            ┆ Rossas     ┆   ┆            ┆         ┆           ┆           │
└──────────┴──────────┴────────────┴────────────┴───┴────────────┴─────────┴───────────┴───────────┘

In [245]:
# We detect the columns called poor as they do not have enough instances with data
poor_columns = poor_columns(df_house)

['Floor',
 'GrossArea',
 'PublishDate',
 'Garage',
 'Elevator',
 'ElectricCarsCharging',
 'NumberOfBedrooms',
 'NumberOfWC',
 'ConservationStatus',
 'LotSize',
 'BuiltArea']

In [246]:
# We select the columns that we need 
df_house = df_house.select(['Price','District','City','Town','Type','EnergyCertificate','Floor','Lift','Parking',
                            'ConstructionYear','TotalArea','LivingArea','TotalRooms','NumberOfBathrooms'])

In [247]:
# We drop the rows with null price 
df_house = df_house.filter(pl.col("Price").is_not_null())

# We convert the category of some columns and rename
df_house = df_house.with_columns([
    pl.col('Parking').cast(pl.Int64),
    pl.col('ConstructionYear').cast(pl.Int64),
    pl.col('TotalRooms').cast(pl.Int64),
    pl.col('NumberOfBathrooms').cast(pl.Int64)
])

df_house = df_house.rename({
    'Parking': 'No.Parkings',
    'NumberOfBathrooms': 'No.Bathrooms'
})

## Imputation of nulls

In [248]:
# We asume that a null value on 'Lift' means that there is no lift
# When null value appears in 'Floor' it means the property has no floor
# We impute the null values on other variables in a coherent way
# We also impute the value of the 'TotalArea' to the 'LivingArea' when it is missing.

df_house = df_house.with_columns(
            pl.col('Lift').fill_null(False), 
            pl.col('Floor').fill_null('no'),
            pl.col('No.Parkings').fill_null(0), 
            pl.col("TotalArea").fill_null(5),
            pl.col("TotalRooms").fill_null(0),
            pl.col("No.Bathrooms").fill_null(0)
)

df_house = df_house.with_columns(
    pl.when(pl.col('LivingArea').is_null())
    .then(pl.col('TotalArea'))  
    .otherwise(pl.col('LivingArea')) 
    .alias('LivingArea')
)

In [249]:
df_house.sample(2)

shape: (2, 14)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Price    ┆ District ┆ City       ┆ Town      ┆ … ┆ TotalArea ┆ LivingAre ┆ TotalRoom ┆ No.Bathro │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ a         ┆ s         ┆ oms       │
│ f64      ┆ str      ┆ str        ┆ str       ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---       │
│          ┆          ┆            ┆           ┆   ┆           ┆ f64       ┆ i64       ┆ i64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 189000.0 ┆ Aveiro   ┆ São João   ┆ São João  ┆ … ┆ 142.0     ┆ 142.0     ┆ 8         ┆ 3         │
│          ┆          ┆ da Madeira ┆ da        ┆   ┆           ┆           ┆           ┆           │
│          ┆          ┆            ┆ Madeira   ┆   ┆           ┆           ┆           ┆           │
│ 325000.0 ┆ Porto    ┆ Gondomar   ┆ Baguim do ┆ … ┆ 196.0     ┆ 196.0     ┆ 0         ┆ 2         │
│          ┆          ┆            ┆ Monte     ┆   ┆           ┆           ┆           ┆           │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Encoding qualitative variables

Now, we encode all qualitative variables in order to being able to train the model.

In [250]:
current_year = datetime.now().year

df_house = df_house.with_columns([
    pl.col('District').cast(pl.Categorical).to_physical().alias('District_encoded'),
    pl.col('City').cast(pl.Categorical).to_physical().alias('City_encoded'),
    pl.col('Town').cast(pl.Categorical).to_physical().alias('Town_encoded'),
    pl.col('Type').cast(pl.Categorical).to_physical().alias('Type_encoded'),
    pl.col('Lift').cast(pl.Int32).alias('Lift_encoded'),
    (current_year - pl.col('ConstructionYear')).alias('Property_Age')
])

floor_encoded = [codificar_floor(floor) for floor in df_house['Floor']]
df_house = df_house.with_columns(pl.Series('Floor_encoded', floor_encoded))

energy_encoded = [codificar_energy_certificate(cert) for cert in df_house['EnergyCertificate']]
df_house = df_house.with_columns(pl.Series('EnergyCertificate_encoded', energy_encoded))

# As we have many nulls on the ConstructionYear columns and this implies several null values in Property_Age, we impute them with the mean age
df_house = df_house.with_columns(pl.col('Property_Age').fill_null(round(df_house['Property_Age'].mean(),0)))

In [251]:
df_house.sample(3)

shape: (3, 22)
┌──────────┬──────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ Price    ┆ District ┆ City   ┆ Town       ┆ … ┆ Lift_encod ┆ Property_A ┆ Floor_enco ┆ EnergyCer │
│ ---      ┆ ---      ┆ ---    ┆ ---        ┆   ┆ ed         ┆ ge         ┆ ded        ┆ tificate_ │
│ f64      ┆ str      ┆ str    ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ encoded   │
│          ┆          ┆        ┆            ┆   ┆ i32        ┆ f64        ┆ f64        ┆ ---       │
│          ┆          ┆        ┆            ┆   ┆            ┆            ┆            ┆ i64       │
╞══════════╪══════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 235000.0 ┆ Santarém ┆ Torres ┆ Torres     ┆ … ┆ 0          ┆ 24.0       ┆ 2.0        ┆ 5         │
│          ┆          ┆ Novas  ┆ Novas      ┆   ┆            ┆            ┆            ┆           │
│          ┆          ┆        ┆ (Santa     ┆   ┆            ┆            ┆            ┆           │
│          ┆          ┆        ┆ Maria,     ┆   ┆            ┆            ┆            ┆           │
│          ┆          ┆        ┆ Sal…       ┆   ┆            ┆            ┆            ┆           │
│ 160000.0 ┆ Santarém ┆ Tomar  ┆ Carregueir ┆ … ┆ 0          ┆ 44.0       ┆ 0.0        ┆ 7         │
│          ┆          ┆        ┆ os         ┆   ┆            ┆            ┆            ┆           │
│ 379000.0 ┆ Porto    ┆ Porto  ┆ Cedofeita, ┆ … ┆ 0          ┆ 36.0       ┆ 0.0        ┆ 5         │
│          ┆          ┆        ┆ Santo      ┆   ┆            ┆            ┆            ┆           │
│          ┆          ┆        ┆ Ildefonso, ┆   ┆            ┆            ┆            ┆           │
│          ┆          ┆        ┆ Sé…        ┆   ┆            ┆            ┆            ┆           │
└──────────┴──────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

## Outliers
Here we filter out the anomalous values that do not make apparent sense.

In [252]:
df_house = df_house.filter(
    (pl.col('Price') <= 100_000_000) &  # Reasonable prices
    (pl.col('Town').is_not_null()) &
    (pl.col('Type').is_not_null()) &
    (pl.col('TotalArea') >= 5) & (pl.col('TotalArea') <= 200_000_000) &  # Reasonable Total Area (m2)
    (pl.col('LivingArea') >= 5) & (pl.col('LivingArea') <= 200_000_000) &  # Reasonable Living Area (m2)
    (pl.col('TotalRooms') <= 100) &  # Reasonable Number of rooms
    (pl.col('No.Bathrooms') >= 0) # Drop negative values
)

In [253]:
df_house.describe()

shape: (9, 23)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ Price     ┆ District ┆ City     ┆ … ┆ Lift_enco ┆ Property_ ┆ Floor_enc ┆ EnergyCer │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ ded       ┆ Age       ┆ oded      ┆ tificate_ │
│ str        ┆ f64       ┆ str      ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ encoded   │
│            ┆           ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 113102.0  ┆ 113102   ┆ 113102   ┆ … ┆ 113102.0  ┆ 113102.0  ┆ 113016.0  ┆ 113102.0  │
│ null_count ┆ 0.0       ┆ 0        ┆ 0        ┆ … ┆ 0.0       ┆ 0.0       ┆ 86.0      ┆ 0.0       │
│ mean       ┆ 353141.11 ┆ null     ┆ null     ┆ … ┆ 0.147486  ┆ 36.11586  ┆ 0.517829  ┆ 2.249775  │
│            ┆ 5238      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ std        ┆ 631389.56 ┆ null     ┆ null     ┆ … ┆ 0.354592  ┆ 21.417469 ┆ 1.61516   ┆ 3.365157  │
│            ┆ 0841      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ min        ┆ 100.0     ┆ Aveiro   ┆ Abrantes ┆ … ┆ 0.0       ┆ 1.0       ┆ -1.0      ┆ -1.0      │
│ 25%        ┆ 77500.0   ┆ null     ┆ null     ┆ … ┆ 0.0       ┆ 25.0      ┆ 0.0       ┆ -1.0      │
│ 50%        ┆ 200000.0  ┆ null     ┆ null     ┆ … ┆ 0.0       ┆ 36.0      ┆ 0.0       ┆ 2.0       │
│ 75%        ┆ 390000.0  ┆ null     ┆ null     ┆ … ┆ 0.0       ┆ 38.0      ┆ 0.0       ┆ 6.0       │
│ max        ┆ 3.6e7     ┆ Évora    ┆ Óbidos   ┆ … ┆ 1.0       ┆ 125.0     ┆ 15.0      ┆ 9.0       │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [254]:
# We verify that LivingArea and TotalArea are not redundant
corr = df_house[["LivingArea", "TotalArea"]].corr()
print(corr)

shape: (2, 2)
┌────────────┬───────────┐
│ LivingArea ┆ TotalArea │
│ ---        ┆ ---       │
│ f64        ┆ f64       │
╞════════════╪═══════════╡
│ 1.0        ┆ 0.584311  │
│ 0.584311   ┆ 1.0       │
└────────────┴───────────┘

## Preparing the dataset for the model
We transform the target column (price) to a logarithmic scale so that the model can better capture the distributions. After that, we create the dataset by selecting from the original one the variables that the model will use.

In [255]:
c = 1000
df_house = df_house.with_columns(
    np.log1p(df_house['Price'] + c).alias('Price_log')
)

In [256]:
df_house_clean = df_house.select(['Price','Price_log','District_encoded','City_encoded','Town_encoded','Type_encoded',
                                  'EnergyCertificate_encoded','Floor_encoded','Property_Age','Lift_encoded',
                                  'TotalArea','LivingArea','TotalRooms','No.Bathrooms','No.Parkings'])

In [257]:
df_house_clean.describe()

shape: (9, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ Price     ┆ Price_log ┆ District_ ┆ … ┆ LivingAre ┆ TotalRoom ┆ No.Bathro ┆ No.Parki │
│ ---       ┆ ---       ┆ ---       ┆ encoded   ┆   ┆ a         ┆ s         ┆ oms       ┆ ngs      │
│ str       ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 113102.0  ┆ 113102.0  ┆ 113102.0  ┆ … ┆ 113102.0  ┆ 113102.0  ┆ 113102.0  ┆ 113102.0 │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 353141.11 ┆ 12.080694 ┆ 7.044341  ┆ … ┆ 6690.5095 ┆ 1.745937  ┆ 1.432406  ┆ 0.582934 │
│           ┆ 5238      ┆           ┆           ┆   ┆ 58        ┆           ┆           ┆          │
│ std       ┆ 631389.56 ┆ 1.23774   ┆ 5.30899   ┆ … ┆ 591113.80 ┆ 2.463621  ┆ 1.697764  ┆ 0.883741 │
│           ┆ 0841      ┆           ┆           ┆   ┆ 7275      ┆           ┆           ┆          │
│ min       ┆ 100.0     ┆ 7.003974  ┆ 0.0       ┆ … ┆ 5.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 25%       ┆ 77500.0   ┆ 11.270867 ┆ 3.0       ┆ … ┆ 79.0      ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ 200000.0  ┆ 12.211065 ┆ 4.0       ┆ … ┆ 132.0     ┆ 1.0       ┆ 1.0       ┆ 0.0      │
│ 75%       ┆ 390000.0  ┆ 12.876465 ┆ 12.0      ┆ … ┆ 309.0     ┆ 3.0       ┆ 2.0       ┆ 1.0      │
│ max       ┆ 3.6e7     ┆ 17.399057 ┆ 24.0      ┆ … ┆ 1.656206e ┆ 97.0      ┆ 90.0      ┆ 3.0      │
│           ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Training the model

We split the data into 3 groups: **training (60%)**, **validation (20%)** and **test (20%)**.

In [258]:
X = df_house_clean.drop(['Price_log','Price'])
y = df_house_clean['Price_log']

# First we split into training and test with a 80/20 proportion
X_train_full, X_test, y_train_full, y_test = train_test_split(X.to_pandas(), y.to_pandas(), test_size=0.2, random_state=42)

# After that we split the training data into training and validation with a 75/25 proportion
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.25, random_state=42)

In [259]:
model = lgb.LGBMRegressor(n_estimators=1000, learning_rate=0.05, max_depth=10, random_state=42)

model.fit(X_train, y_train, eval_set=[(X_val, y_val)], eval_metric='rmse', callbacks=[early_stopping(stopping_rounds=50), log_evaluation(period=10)])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002856 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1228
[LightGBM] [Info] Number of data points in the train set: 67860, number of used features: 13
[LightGBM] [Info] Start training from score 12.081381
Training until validation scores don't improve for 50 rounds
[10]	valid_0's rmse: 1.00169	valid_0's l2: 1.00338
[20]	valid_0's rmse: 0.883392	valid_0's l2: 0.780381
[30]	valid_0's rmse: 0.817738	valid_0's l2: 0.668695
[40]	valid_0's rmse: 0.776607	valid_0's l2: 0.603119
[50]	valid_0's rmse: 0.747965	valid_0's l2: 0.559451
[60]	valid_0's rmse: 0.726936	valid_0's l2: 0.528436
[70]	valid_0's rmse: 0.711537	valid_0's l2: 0.506285
[80]	valid_0's rmse: 0.700426	valid_0's l2: 0.490597
[90]	valid_0's rmse: 0.691303	valid_0's l2: 0.4779
[100]	valid_0's rmse: 0.685388	valid_0's l2: 0.469757
[110]	valid_0's rmse: 0.67894	valid_0's l2: 0.46096
[120]	valid_0's rmse: 0.673818	valid_0's l2: 0.45403
[130]	valid_0's rmse: 0.669298	valid_0's l2: 0.44796
[140]	valid_0's rmse: 0.665448	valid_0's l2: 0.442822
[150]	valid_0's rmse: 0.661447	valid_0's l2: 0.437512
[160]	valid_0's rmse: 0.657614	valid_0's l2: 0.432457
[170]	valid_0's rmse: 0.654812	valid_0's l2: 0.428779
[180]	valid_0's rmse: 0.651485	valid_0's l2: 0.424433
[190]	valid_0's rmse: 0.64924	valid_0's l2: 0.421513
[200]	valid_0's rmse: 0.646856	valid_0's l2: 0.418422
[210]	valid_0's rmse: 0.644352	valid_0's l2: 0.415189
[220]	valid_0's rmse: 0.642246	valid_0's l2: 0.41248
[230]	valid_0's rmse: 0.640436	valid_0's l2: 0.410159
[240]	valid_0's rmse: 0.638905	valid_0's l2: 0.408199
[250]	valid_0's rmse: 0.636815	valid_0's l2: 0.405533
[260]	valid_0's rmse: 0.634725	valid_0's l2: 0.402876
[270]	valid_0's rmse: 0.633014	valid_0's l2: 0.400706
[280]	valid_0's rmse: 0.630948	valid_0's l2: 0.398095
[290]	valid_0's rmse: 0.629104	valid_0's l2: 0.395772
[300]	valid_0's rmse: 0.627634	valid_0's l2: 0.393925
[310]	valid_0's rmse: 0.626253	valid_0's l2: 0.392193
[320]	valid_0's rmse: 0.624457	valid_0's l2: 0.389946
[330]	valid_0's rmse: 0.623333	valid_0's l2: 0.388544
[340]	valid_0's rmse: 0.621791	valid_0's l2: 0.386624
[350]	valid_0's rmse: 0.620646	valid_0's l2: 0.385201
[360]	valid_0's rmse: 0.619576	valid_0's l2: 0.383874
[370]	valid_0's rmse: 0.618448	valid_0's l2: 0.382478
[380]	valid_0's rmse: 0.617313	valid_0's l2: 0.381075
[390]	valid_0's rmse: 0.616303	valid_0's l2: 0.379829
[400]	valid_0's rmse: 0.615269	valid_0's l2: 0.378555
[410]	valid_0's rmse: 0.614035	valid_0's l2: 0.37704
[420]	valid_0's rmse: 0.613118	valid_0's l2: 0.375914
[430]	valid_0's rmse: 0.612314	valid_0's l2: 0.374928
[440]	valid_0's rmse: 0.611396	valid_0's l2: 0.373805
[450]	valid_0's rmse: 0.610459	valid_0's l2: 0.37266
[460]	valid_0's rmse: 0.609455	valid_0's l2: 0.371435
[470]	valid_0's rmse: 0.608586	valid_0's l2: 0.370377
[480]	valid_0's rmse: 0.607624	valid_0's l2: 0.369207
[490]	valid_0's rmse: 0.606591	valid_0's l2: 0.367952
[500]	valid_0's rmse: 0.605853	valid_0's l2: 0.367058
[510]	valid_0's rmse: 0.604884	valid_0's l2: 0.365885
[520]	valid_0's rmse: 0.604023	valid_0's l2: 0.364844
[530]	valid_0's rmse: 0.603094	valid_0's l2: 0.363723
[540]	valid_0's rmse: 0.602537	valid_0's l2: 0.363051
[550]	valid_0's rmse: 0.601759	valid_0's l2: 0.362114
[560]	valid_0's rmse: 0.601184	valid_0's l2: 0.361422
[570]	valid_0's rmse: 0.600456	valid_0's l2: 0.360547
[580]	valid_0's rmse: 0.599569	valid_0's l2: 0.359483
[590]	valid_0's rmse: 0.599204	valid_0's l2: 0.359045
[600]	valid_0's rmse: 0.598542	valid_0's l2: 0.358252
[610]	valid_0's rmse: 0.597959	valid_0's l2: 0.357555
[620]	valid_0's rmse: 0.597462	valid_0's l2: 0.356961
[630]	valid_0's rmse: 0.596877	valid_0's l2: 0.356262
[640]	valid_0's rmse: 0.596304	valid_0's l2: 0.355578
[650]	valid_0's rmse: 0.595767	valid_0's l2: 0.354938
[660]	valid_0's rmse: 0.595396	valid_0's l2: 0.354496
[670]	valid_0's rmse: 0.594744	valid_0's l2: 0.353721
[680]	valid_0's rmse: 0.594107	valid_0's l2: 0.352963
[690]	valid_0's rmse: 0.593665	valid_0's l2: 0.352438
[700]	valid_0's rmse: 0.593158	valid_0's l2: 0.351837
[710]	valid_0's rmse: 0.592724	valid_0's l2: 0.351321
[720]	valid_0's rmse: 0.592128	valid_0's l2: 0.350616
[730]	valid_0's rmse: 0.591578	valid_0's l2: 0.349965
[740]	valid_0's rmse: 0.591153	valid_0's l2: 0.349462
[750]	valid_0's rmse: 0.590694	valid_0's l2: 0.348919
[760]	valid_0's rmse: 0.590406	valid_0's l2: 0.348579
[770]	valid_0's rmse: 0.589823	valid_0's l2: 0.347891
[780]	valid_0's rmse: 0.589399	valid_0's l2: 0.347391
[790]	valid_0's rmse: 0.588908	valid_0's l2: 0.346813
[800]	valid_0's rmse: 0.588522	valid_0's l2: 0.346358
[810]	valid_0's rmse: 0.58818	valid_0's l2: 0.345955
[820]	valid_0's rmse: 0.587711	valid_0's l2: 0.345404
[830]	valid_0's rmse: 0.587274	valid_0's l2: 0.34489
[840]	valid_0's rmse: 0.586917	valid_0's l2: 0.344471
[850]	valid_0's rmse: 0.586698	valid_0's l2: 0.344215
[860]	valid_0's rmse: 0.586353	valid_0's l2: 0.34381
[870]	valid_0's rmse: 0.586103	valid_0's l2: 0.343516
[880]	valid_0's rmse: 0.58572	valid_0's l2: 0.343068
[890]	valid_0's rmse: 0.58551	valid_0's l2: 0.342822
[900]	valid_0's rmse: 0.585187	valid_0's l2: 0.342444
[910]	valid_0's rmse: 0.58494	valid_0's l2: 0.342155
[920]	valid_0's rmse: 0.584423	valid_0's l2: 0.341551
[930]	valid_0's rmse: 0.584184	valid_0's l2: 0.34127
[940]	valid_0's rmse: 0.58392	valid_0's l2: 0.340963
[950]	valid_0's rmse: 0.583586	valid_0's l2: 0.340573
[960]	valid_0's rmse: 0.58319	valid_0's l2: 0.340111
[970]	valid_0's rmse: 0.582709	valid_0's l2: 0.339549
[980]	valid_0's rmse: 0.582448	valid_0's l2: 0.339245
[990]	valid_0's rmse: 0.582161	valid_0's l2: 0.338911
[1000]	valid_0's rmse: 0.581754	valid_0's l2: 0.338438
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 0.581754	valid_0's l2: 0.338438

LGBMRegressor(learning_rate=0.05, max_depth=10, n_estimators=1000,
              random_state=42)

## Evaluating the model

We evaluate how good is the model on predicting the price of a property.

In [260]:
y_pred = model.predict(X_test)
y_pred_original = np.expm1(y_pred) - c
y_test_original = np.expm1(y_test) - c

mae_original = mean_absolute_error(y_test_original, y_pred_original)
mse_original = mean_squared_error(y_test_original, y_pred_original)
rmse_original = np.sqrt(mse_original)
r2_original = r2_score(y_test_original, y_pred_original)

print(f"Mean Absolute Error (Original Scale): {mae_original:.4f}")
print(f"Mean Squared Error (Original Scale): {mse_original:.4f}")
print(f"Root Mean Squared Error (Original Scale): {rmse_original:.4f}")
print(f"R-squared (Original Scale): {r2_original:.4f}")

Mean Absolute Error (Original Scale): 122815.7026
Mean Squared Error (Original Scale): 178247466922.7449
Root Mean Squared Error (Original Scale): 422193.6368
R-squared (Original Scale): 0.5291

As we can see, the model's evaluation metrics are somewhat poor. An RMSE value of around €400,000 is not ideal for predicting property prices. This is due to the wide range of prices, which span from €100 to €36M, making it difficult for the model to accurately capture the distribution. Consequently, we will implement improvement measures to refine the prediction.

## Splitting the dataset into three ranges

As we have seen, the model is not entirely effective due to the wide range of prices and their heterogeneous distribution (with more prices in the lower range than in the higher range). Therefore, we decided to split the dataset into three groups: low prices, high prices, and ultra-high prices. We will train a model for each group and compare the results with the previous model to determine if we have achieved any improvement.

In [261]:
df_low = df_house_clean.filter(pl.col('Price') <= 1_000_000)
df_high = df_house_clean.filter(pl.col('Price').is_between(1_000_000, 5_000_000, closed='right'))
df_uhigh = df_house_clean.filter(pl.col('Price') > 5_000_000)

# Low prices
X_low = df_low.drop(['Price_log','Price'])
y_low = df_low['Price_log']

X_train_full_low, X_test_low, y_train_full_low, y_test_low = train_test_split(X_low.to_pandas(), y_low.to_pandas(), test_size=0.2, random_state=42)
X_train_low, X_val_low, y_train_low, y_val_low = train_test_split(X_train_full_low, y_train_full_low, test_size=0.25, random_state=42)

# High prices
X_high = df_high.drop(['Price_log','Price'])
y_high = df_high['Price_log']

X_train_full_high, X_test_high, y_train_full_high, y_test_high = train_test_split(X_high.to_pandas(), y_high.to_pandas(), test_size=0.2, random_state=42)
X_train_high, X_val_high, y_train_high, y_val_high = train_test_split(X_train_full_high, y_train_full_high, test_size=0.25, random_state=42)

# Ultra high prices
X_uhigh = df_uhigh.drop(['Price_log','Price'])
y_uhigh = df_uhigh['Price_log']

X_train_full_uhigh, X_test_uhigh, y_train_full_uhigh, y_test_uhigh = train_test_split(X_uhigh.to_pandas(), y_uhigh.to_pandas(), test_size=0.2, random_state=42)
X_train_uhigh, X_val_uhigh, y_train_uhigh, y_val_uhigh = train_test_split(X_train_full_uhigh, y_train_full_uhigh, test_size=0.25, random_state=42)

### Low prices

In [262]:
model_low = lgb.LGBMRegressor(n_estimators=1000, learning_rate=0.05, max_depth=10, random_state=42)
model_low.fit(X_train_low, y_train_low, eval_set=[(X_val_low, y_val_low)], eval_metric='rmse', callbacks=[early_stopping(stopping_rounds=50), log_evaluation(period=10)])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001331 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1208
[LightGBM] [Info] Number of data points in the train set: 63951, number of used features: 13
[LightGBM] [Info] Start training from score 11.936602
Training until validation scores don't improve for 50 rounds
[10]	valid_0's rmse: 0.903362	valid_0's l2: 0.816063
[20]	valid_0's rmse: 0.796307	valid_0's l2: 0.634105
[30]	valid_0's rmse: 0.737035	valid_0's l2: 0.543221
[40]	valid_0's rmse: 0.702405	valid_0's l2: 0.493373
[50]	valid_0's rmse: 0.678585	valid_0's l2: 0.460478
[60]	valid_0's rmse: 0.662375	valid_0's l2: 0.438741
[70]	valid_0's rmse: 0.649284	valid_0's l2: 0.42157
[80]	valid_0's rmse: 0.639066	valid_0's l2: 0.408406
[90]	valid_0's rmse: 0.630996	valid_0's l2: 0.398156
[100]	valid_0's rmse: 0.625032	valid_0's l2: 0.390666
[110]	valid_0's rmse: 0.619907	valid_0's l2: 0.384285
[120]	valid_0's rmse: 0.615454	valid_0's l2: 0.378784
[130]	valid_0's rmse: 0.611009	valid_0's l2: 0.373332
[140]	valid_0's rmse: 0.607576	valid_0's l2: 0.369149
[150]	valid_0's rmse: 0.60437	valid_0's l2: 0.365263
[160]	valid_0's rmse: 0.601947	valid_0's l2: 0.36234
[170]	valid_0's rmse: 0.599654	valid_0's l2: 0.359585
[180]	valid_0's rmse: 0.597535	valid_0's l2: 0.357048
[190]	valid_0's rmse: 0.595266	valid_0's l2: 0.354341
[200]	valid_0's rmse: 0.593252	valid_0's l2: 0.351948
[210]	valid_0's rmse: 0.591358	valid_0's l2: 0.349705
[220]	valid_0's rmse: 0.589307	valid_0's l2: 0.347283
[230]	valid_0's rmse: 0.587784	valid_0's l2: 0.34549
[240]	valid_0's rmse: 0.586319	valid_0's l2: 0.34377
[250]	valid_0's rmse: 0.584614	valid_0's l2: 0.341773
[260]	valid_0's rmse: 0.583317	valid_0's l2: 0.340259
[270]	valid_0's rmse: 0.581371	valid_0's l2: 0.337993
[280]	valid_0's rmse: 0.579951	valid_0's l2: 0.336343
[290]	valid_0's rmse: 0.578957	valid_0's l2: 0.335191
[300]	valid_0's rmse: 0.577659	valid_0's l2: 0.333689
[310]	valid_0's rmse: 0.576446	valid_0's l2: 0.33229
[320]	valid_0's rmse: 0.575142	valid_0's l2: 0.330789
[330]	valid_0's rmse: 0.573902	valid_0's l2: 0.329363
[340]	valid_0's rmse: 0.572814	valid_0's l2: 0.328116
[350]	valid_0's rmse: 0.571919	valid_0's l2: 0.327091
[360]	valid_0's rmse: 0.570749	valid_0's l2: 0.325754
[370]	valid_0's rmse: 0.569761	valid_0's l2: 0.324628
[380]	valid_0's rmse: 0.568875	valid_0's l2: 0.323619
[390]	valid_0's rmse: 0.568056	valid_0's l2: 0.322687
[400]	valid_0's rmse: 0.56693	valid_0's l2: 0.32141
[410]	valid_0's rmse: 0.566086	valid_0's l2: 0.320453
[420]	valid_0's rmse: 0.565483	valid_0's l2: 0.319771
[430]	valid_0's rmse: 0.564516	valid_0's l2: 0.318678
[440]	valid_0's rmse: 0.563688	valid_0's l2: 0.317744
[450]	valid_0's rmse: 0.56288	valid_0's l2: 0.316834
[460]	valid_0's rmse: 0.562099	valid_0's l2: 0.315956
[470]	valid_0's rmse: 0.561486	valid_0's l2: 0.315267
[480]	valid_0's rmse: 0.56092	valid_0's l2: 0.314632
[490]	valid_0's rmse: 0.560013	valid_0's l2: 0.313614
[500]	valid_0's rmse: 0.559155	valid_0's l2: 0.312654
[510]	valid_0's rmse: 0.558442	valid_0's l2: 0.311858
[520]	valid_0's rmse: 0.557781	valid_0's l2: 0.31112
[530]	valid_0's rmse: 0.557141	valid_0's l2: 0.310406
[540]	valid_0's rmse: 0.556494	valid_0's l2: 0.309686
[550]	valid_0's rmse: 0.556043	valid_0's l2: 0.309184
[560]	valid_0's rmse: 0.555343	valid_0's l2: 0.308406
[570]	valid_0's rmse: 0.554566	valid_0's l2: 0.307543
[580]	valid_0's rmse: 0.554027	valid_0's l2: 0.306946
[590]	valid_0's rmse: 0.553574	valid_0's l2: 0.306444
[600]	valid_0's rmse: 0.5532	valid_0's l2: 0.306031
[610]	valid_0's rmse: 0.552781	valid_0's l2: 0.305567
[620]	valid_0's rmse: 0.552237	valid_0's l2: 0.304966
[630]	valid_0's rmse: 0.551812	valid_0's l2: 0.304496
[640]	valid_0's rmse: 0.551146	valid_0's l2: 0.303762
[650]	valid_0's rmse: 0.550722	valid_0's l2: 0.303294
[660]	valid_0's rmse: 0.550112	valid_0's l2: 0.302624
[670]	valid_0's rmse: 0.549504	valid_0's l2: 0.301955
[680]	valid_0's rmse: 0.549144	valid_0's l2: 0.301559
[690]	valid_0's rmse: 0.548862	valid_0's l2: 0.301249
[700]	valid_0's rmse: 0.548434	valid_0's l2: 0.300779
[710]	valid_0's rmse: 0.548025	valid_0's l2: 0.300331
[720]	valid_0's rmse: 0.547662	valid_0's l2: 0.299933
[730]	valid_0's rmse: 0.547165	valid_0's l2: 0.299389
[740]	valid_0's rmse: 0.546734	valid_0's l2: 0.298918
[750]	valid_0's rmse: 0.546362	valid_0's l2: 0.298511
[760]	valid_0's rmse: 0.545787	valid_0's l2: 0.297884
[770]	valid_0's rmse: 0.545278	valid_0's l2: 0.297328
[780]	valid_0's rmse: 0.544864	valid_0's l2: 0.296877
[790]	valid_0's rmse: 0.544371	valid_0's l2: 0.296339
[800]	valid_0's rmse: 0.543983	valid_0's l2: 0.295918
[810]	valid_0's rmse: 0.543649	valid_0's l2: 0.295555
[820]	valid_0's rmse: 0.543372	valid_0's l2: 0.295253
[830]	valid_0's rmse: 0.542883	valid_0's l2: 0.294722
[840]	valid_0's rmse: 0.542674	valid_0's l2: 0.294495
[850]	valid_0's rmse: 0.542311	valid_0's l2: 0.294101
[860]	valid_0's rmse: 0.541937	valid_0's l2: 0.293696
[870]	valid_0's rmse: 0.541705	valid_0's l2: 0.293444
[880]	valid_0's rmse: 0.541325	valid_0's l2: 0.293032
[890]	valid_0's rmse: 0.540967	valid_0's l2: 0.292645
[900]	valid_0's rmse: 0.540597	valid_0's l2: 0.292245
[910]	valid_0's rmse: 0.540373	valid_0's l2: 0.292003
[920]	valid_0's rmse: 0.539903	valid_0's l2: 0.291495
[930]	valid_0's rmse: 0.539639	valid_0's l2: 0.29121
[940]	valid_0's rmse: 0.539357	valid_0's l2: 0.290907
[950]	valid_0's rmse: 0.538992	valid_0's l2: 0.290512
[960]	valid_0's rmse: 0.538697	valid_0's l2: 0.290195
[970]	valid_0's rmse: 0.538329	valid_0's l2: 0.289798
[980]	valid_0's rmse: 0.537971	valid_0's l2: 0.289413
[990]	valid_0's rmse: 0.537698	valid_0's l2: 0.289119
[1000]	valid_0's rmse: 0.537349	valid_0's l2: 0.288744
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 0.537349	valid_0's l2: 0.288744

LGBMRegressor(learning_rate=0.05, max_depth=10, n_estimators=1000,
              random_state=42)

In [263]:
y_pred_low = model_low.predict(X_test_low)
y_pred_original_low = np.expm1(y_pred_low) - c
y_test_original_low = np.expm1(y_test_low) - c

mae_original_low = mean_absolute_error(y_test_original_low, y_pred_original_low)
mse_original_low = mean_squared_error(y_test_original_low, y_pred_original_low)
rmse_original_low = np.sqrt(mse_original_low)
r2_original_low = r2_score(y_test_original_low, y_pred_original_low)

print(f"Mean Absolute Error (Original Scale): {mae_original_low:.4f}")
print(f"Mean Squared Error (Original Scale): {mse_original_low:.4f}")
print(f"Root Mean Squared Error (Original Scale): {rmse_original_low:.4f}")
print(f"R-squared (Original Scale): {r2_original_low:.4f}")

Mean Absolute Error (Original Scale): 65394.1374
Mean Squared Error (Original Scale): 13268569722.3259
Root Mean Squared Error (Original Scale): 115189.2778
R-squared (Original Scale): 0.7192

### High prices

In [264]:
model_high = lgb.LGBMRegressor(n_estimators=1000, learning_rate=0.05, max_depth=10, random_state=42)
model_high.fit(X_train_high, y_train_high, eval_set=[(X_val_high, y_val_high)], eval_metric='rmse', callbacks=[early_stopping(stopping_rounds=50), log_evaluation(period=10)])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000409 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1122
[LightGBM] [Info] Number of data points in the train set: 3756, number of used features: 13
[LightGBM] [Info] Start training from score 14.352916
Training until validation scores don't improve for 50 rounds
[10]	valid_0's rmse: 0.334249	valid_0's l2: 0.111723
[20]	valid_0's rmse: 0.320532	valid_0's l2: 0.102741
[30]	valid_0's rmse: 0.311156	valid_0's l2: 0.0968181
[40]	valid_0's rmse: 0.30561	valid_0's l2: 0.0933977
[50]	valid_0's rmse: 0.30161	valid_0's l2: 0.0909684
[60]	valid_0's rmse: 0.298879	valid_0's l2: 0.0893284
[70]	valid_0's rmse: 0.296226	valid_0's l2: 0.0877499
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[80]	valid_0's rmse: 0.29458	valid_0's l2: 0.0867772
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[90]	valid_0's rmse: 0.293207	valid_0's l2: 0.0859706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[100]	valid_0's rmse: 0.29192	valid_0's l2: 0.0852171
[110]	valid_0's rmse: 0.290516	valid_0's l2: 0.0843997
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[120]	valid_0's rmse: 0.289583	valid_0's l2: 0.0838582
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[130]	valid_0's rmse: 0.288603	valid_0's l2: 0.0832915
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[140]	valid_0's rmse: 0.287697	valid_0's l2: 0.0827693
[150]	valid_0's rmse: 0.286632	valid_0's l2: 0.0821576
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[160]	valid_0's rmse: 0.285877	valid_0's l2: 0.0817258
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[170]	valid_0's rmse: 0.285295	valid_0's l2: 0.0813931
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[180]	valid_0's rmse: 0.284341	valid_0's l2: 0.0808496
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[190]	valid_0's rmse: 0.283377	valid_0's l2: 0.0803028
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[200]	valid_0's rmse: 0.282546	valid_0's l2: 0.0798325
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[210]	valid_0's rmse: 0.282313	valid_0's l2: 0.0797009
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[220]	valid_0's rmse: 0.281855	valid_0's l2: 0.0794424
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[230]	valid_0's rmse: 0.281587	valid_0's l2: 0.079291
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[240]	valid_0's rmse: 0.281137	valid_0's l2: 0.079038
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[250]	valid_0's rmse: 0.280795	valid_0's l2: 0.0788457
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[260]	valid_0's rmse: 0.280581	valid_0's l2: 0.0787257
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[270]	valid_0's rmse: 0.279963	valid_0's l2: 0.0783791
[280]	valid_0's rmse: 0.27921	valid_0's l2: 0.077958
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[290]	valid_0's rmse: 0.278697	valid_0's l2: 0.0776721
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[300]	valid_0's rmse: 0.278234	valid_0's l2: 0.0774139
[310]	valid_0's rmse: 0.27781	valid_0's l2: 0.0771785
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[320]	valid_0's rmse: 0.27743	valid_0's l2: 0.0769672
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[330]	valid_0's rmse: 0.27717	valid_0's l2: 0.0768234
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[340]	valid_0's rmse: 0.276935	valid_0's l2: 0.0766932
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[350]	valid_0's rmse: 0.276743	valid_0's l2: 0.0765865
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[360]	valid_0's rmse: 0.276275	valid_0's l2: 0.0763281
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[370]	valid_0's rmse: 0.276215	valid_0's l2: 0.0762947
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[380]	valid_0's rmse: 0.276089	valid_0's l2: 0.0762252
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[390]	valid_0's rmse: 0.275736	valid_0's l2: 0.0760302
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[400]	valid_0's rmse: 0.275248	valid_0's l2: 0.0757614
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[410]	valid_0's rmse: 0.275177	valid_0's l2: 0.0757225
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[420]	valid_0's rmse: 0.275093	valid_0's l2: 0.075676
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[430]	valid_0's rmse: 0.274857	valid_0's l2: 0.0755465
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[440]	valid_0's rmse: 0.274539	valid_0's l2: 0.0753718
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[450]	valid_0's rmse: 0.274146	valid_0's l2: 0.0751558
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[460]	valid_0's rmse: 0.274021	valid_0's l2: 0.0750877
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[470]	valid_0's rmse: 0.273797	valid_0's l2: 0.0749647
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[480]	valid_0's rmse: 0.273708	valid_0's l2: 0.074916
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[490]	valid_0's rmse: 0.273794	valid_0's l2: 0.0749631
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[500]	valid_0's rmse: 0.273773	valid_0's l2: 0.0749516
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[510]	valid_0's rmse: 0.273643	valid_0's l2: 0.0748805
[520]	valid_0's rmse: 0.273487	valid_0's l2: 0.0747953
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[530]	valid_0's rmse: 0.273336	valid_0's l2: 0.0747128
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[540]	valid_0's rmse: 0.273063	valid_0's l2: 0.0745633
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[550]	valid_0's rmse: 0.273054	valid_0's l2: 0.0745584
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[560]	valid_0's rmse: 0.272847	valid_0's l2: 0.0744454
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[570]	valid_0's rmse: 0.272847	valid_0's l2: 0.0744453
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[580]	valid_0's rmse: 0.27267	valid_0's l2: 0.0743488
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[590]	valid_0's rmse: 0.272551	valid_0's l2: 0.0742839
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[600]	valid_0's rmse: 0.272514	valid_0's l2: 0.0742637
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[610]	valid_0's rmse: 0.272348	valid_0's l2: 0.0741732
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[620]	valid_0's rmse: 0.272116	valid_0's l2: 0.0740472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[630]	valid_0's rmse: 0.272041	valid_0's l2: 0.0740064
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[640]	valid_0's rmse: 0.272042	valid_0's l2: 0.0740069
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[650]	valid_0's rmse: 0.27206	valid_0's l2: 0.0740165
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[660]	valid_0's rmse: 0.271957	valid_0's l2: 0.0739604
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[670]	valid_0's rmse: 0.271944	valid_0's l2: 0.0739534
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[680]	valid_0's rmse: 0.271793	valid_0's l2: 0.0738712
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[690]	valid_0's rmse: 0.271678	valid_0's l2: 0.073809
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[700]	valid_0's rmse: 0.271495	valid_0's l2: 0.0737094
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[710]	valid_0's rmse: 0.271674	valid_0's l2: 0.0738067
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[720]	valid_0's rmse: 0.271591	valid_0's l2: 0.0737614

LGBMRegressor(learning_rate=0.05, max_depth=10, n_estimators=1000,
              random_state=42)

In [265]:
y_pred_high = model_high.predict(X_test_high)
y_pred_original_high = np.expm1(y_pred_high) - c
y_test_original_high = np.expm1(y_test_high) - c

mae_original_high = mean_absolute_error(y_test_original_high, y_pred_original_high)
mse_original_high = mean_squared_error(y_test_original_high, y_pred_original_high)
rmse_original_high = np.sqrt(mse_original_high)
r2_original_high = r2_score(y_test_original_high, y_pred_original_high)

print(f"Mean Absolute Error (Original Scale): {mae_original_high:.4f}")
print(f"Mean Squared Error (Original Scale): {mse_original_high:.4f}")
print(f"Root Mean Squared Error (Original Scale): {rmse_original_high:.4f}")
print(f"R-squared (Original Scale): {r2_original_high:.4f}")

Mean Absolute Error (Original Scale): 426315.9572
Mean Squared Error (Original Scale): 403847185840.2635
Root Mean Squared Error (Original Scale): 635489.7213
R-squared (Original Scale): 0.3964

### Ultra-high prices

In [266]:
model_uhigh = lgb.LGBMRegressor(n_estimators=1000, learning_rate=0.05, max_depth=10, random_state=42)
model_uhigh.fit(X_train_uhigh, y_train_uhigh, eval_set=[(X_val_uhigh, y_val_uhigh)], eval_metric='rmse', callbacks=[early_stopping(stopping_rounds=50), log_evaluation(period=10)])

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000579 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 234
[LightGBM] [Info] Number of data points in the train set: 151, number of used features: 11
[LightGBM] [Info] Start training from score 15.878052
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 50 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[10]	valid_0's rmse: 0.292314	valid_0's l2: 0.0854472
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[20]	valid_0's rmse: 0.307423	valid_0's l2: 0.0945088
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[30]	valid_0's rmse: 0.317962	valid_0's l2: 0.1011
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[40]	valid_0's rmse: 0.320663	valid_0's l2: 0.102825
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[50]	valid_0's rmse: 0.323526	valid_0's l2: 0.104669
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Early stopping, best iteration is:
[2]	valid_0's rmse: 0.284419	valid_0's l2: 0.080894

LGBMRegressor(learning_rate=0.05, max_depth=10, n_estimators=1000,
              random_state=42)

In [267]:
y_pred_uhigh = model_uhigh.predict(X_test_uhigh)
y_pred_original_uhigh = np.expm1(y_pred_uhigh) - c
y_test_original_uhigh = np.expm1(y_test_uhigh) - c

mae_original_uhigh = mean_absolute_error(y_test_original_uhigh, y_pred_original_uhigh)
mse_original_uhigh = mean_squared_error(y_test_original_uhigh, y_pred_original_uhigh)
rmse_original_uhigh = np.sqrt(mse_original_uhigh)
r2_original_uhigh = r2_score(y_test_original_uhigh, y_pred_original_uhigh)

print(f"Mean Absolute Error (Original Scale): {mae_original_uhigh:.4f}")
print(f"Mean Squared Error (Original Scale): {mse_original_uhigh:.4f}")
print(f"Root Mean Squared Error (Original Scale): {rmse_original_uhigh:.4f}")
print(f"R-squared (Original Scale): {r2_original_uhigh:.4f}")

Mean Absolute Error (Original Scale): 2728542.7210
Mean Squared Error (Original Scale): 23543852018079.0195
Root Mean Squared Error (Original Scale): 4852200.7397
R-squared (Original Scale): 0.0274

## Conclusions

After analyzing the results obtained, it can be concluded that dividing the data into three ranges and training a model for each range provides some improvement in predictions, especially significantly in the low-price range. It is true that in the ultra-expensive price range, the model does not fit well and the predictions are somewhat poor, but this is due to the greater dispersion of the data in this range. Thanks to the division, we avoid this high dispersion in the high-price range affecting the prediction of prices in other ranges.

In conclusion, we have obtained a good model for the low-price range and a somewhat mediocre one for the high-price range. The model for ultra-high prices is not useful. Regarding the choice of the LightGBM algorithm, it has been selected for its flexibility with variables and its ability to capture patterns in property features. Given the difficulty of the predictions, we cannot say it has been a poor choice, and if better performance is desired, we would need to use more sophisticated algorithms such as neural networks.